Slides for News-September-2023
PyDataLondon/News pull request #5
Opened 2023-09-06 05:46 UTC by pt247

The only thing left is to update upcoming events.

2023-09-19 19:46 UTC, kynan requested changes
I think you can remove those CSS files?

2023-09-19 19:46 UTC, kynan commented on 2023-09-06_PyData-News-September-2023/custom.css
Not referenced?

2023-09-19 19:46 UTC, kynan commented on 2023-09-06_PyData-News-September-2023/styles/custom.css
Not referenced?

2023-09-28 18:26 UTC, kynan commented
@pt247 ?

2023-10-01 08:58 UTC, pt247 commented on 2023-09-06_PyData-News-September-2023/styles/custom.css
Removed.

2023-10-07 21:00 UTC, kynan approved these changes

2023-10-07 21:00 UTC, merged