July PyData London meet-up news.
PyDataLondon/News pull request #7
Opened 2024-07-03 12:07 UTC by mszeszo

2024-07-03 12:08 UTC, mszeszo commented
July 2024 PyData London meet-up slides.

2024-08-12 22:21 UTC, kynan requested changes

2024-08-12 22:21 UTC, kynan commented on 2024-07-02_PyData-News-July-2024/custom.css
This file doesn't appear to be used?

2024-08-12 22:21 UTC, kynan commented on 2024-07-02_PyData-News-July-2024/styles/custom.css
This file appears to be unused?

2024-08-12 22:21 UTC, kynan commented on 2024-07-07_PyData-News-July-2024
Please revert this file

2024-09-26 21:50 UTC, merged